name: Node.js CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display GitHub predefined variables
        run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Branch: $GITHUB_REF_NAME"
           echo "Run ID: $GITHUB_RUN_ID"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: node-ci-demo
        run: npm install

      - name: Run build
        working-directory: node-ci-demo
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-build-output
          path: node-ci-demo/dist